"use strict";

// Dependency-free XLSX reader/writer for the Scout Report's tabular import/export.
// It intentionally supports the simple worksheet shape generated by this project
// and can also read common Excel files that use shared strings or deflate compression.

const zlib = require("zlib");

function xmlEscape(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function xmlUnescape(value) {
  return String(value ?? "")
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function columnName(index) {
  let n = index + 1;
  let out = "";
  while (n > 0) {
    const r = (n - 1) % 26;
    out = String.fromCharCode(65 + r) + out;
    n = Math.floor((n - 1) / 26);
  }
  return out;
}

function columnIndex(ref) {
  const letters = String(ref || "").match(/^[A-Z]+/i)?.[0] || "A";
  let n = 0;
  for (const ch of letters.toUpperCase()) n = n * 26 + ch.charCodeAt(0) - 64;
  return n - 1;
}

function crc32(buffer) {
  let crc = 0xffffffff;
  for (const byte of buffer) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(n) { const b = Buffer.alloc(2); b.writeUInt16LE(n); return b; }
function u32(n) { const b = Buffer.alloc(4); b.writeUInt32LE(n >>> 0); return b; }

function zip(entries) {
  const locals = [];
  const centrals = [];
  let offset = 0;
  for (const [name, raw] of Object.entries(entries)) {
    const nameBuf = Buffer.from(name, "utf8");
    const data = Buffer.isBuffer(raw) ? raw : Buffer.from(raw, "utf8");
    const compressed = zlib.deflateRawSync(data, { level: 6 });
    const crc = crc32(data);
    const local = Buffer.concat([
      Buffer.from([0x50,0x4b,0x03,0x04]), u16(20), u16(0), u16(8), u16(0), u16(0), u32(crc), u32(compressed.length), u32(data.length), u16(nameBuf.length), u16(0), nameBuf, compressed
    ]);
    locals.push(local);
    const central = Buffer.concat([
      Buffer.from([0x50,0x4b,0x01,0x02]), u16(20), u16(20), u16(0), u16(8), u16(0), u16(0), u32(crc), u32(compressed.length), u32(data.length), u16(nameBuf.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), nameBuf
    ]);
    centrals.push(central);
    offset += local.length;
  }
  const centralDir = Buffer.concat(centrals);
  const body = Buffer.concat(locals);
  const eocd = Buffer.concat([
    Buffer.from([0x50,0x4b,0x05,0x06]), Buffer.alloc(2), Buffer.alloc(2), u16(centrals.length), u16(centrals.length), u32(centralDir.length), u32(body.length), u16(0)
  ]);
  return Buffer.concat([body, centralDir, eocd]);
}

function makeWorksheet(rows) {
  const maxCols = rows.reduce((m, r) => Math.max(m, r.length), 0);
  const rowXml = rows.map((row, ri) => {
    const cells = [];
    for (let ci = 0; ci < maxCols; ci++) {
      const value = row[ci] == null ? "" : String(row[ci]);
      cells.push(`<c r="${columnName(ci)}${ri + 1}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(value)}</t></is></c>`);
    }
    return `<row r="${ri + 1}">${cells.join("")}</row>`;
  }).join("");
  const ref = `A1:${columnName(Math.max(0, maxCols - 1))}${Math.max(1, rows.length)}`;
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="${ref}"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetData>${rowXml}</sheetData></worksheet>`;
}

function createWorkbook(rows, sheetName = "Reports") {
  const safeSheet = xmlEscape(sheetName);
  const files = {
    "[Content_Types].xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`,
    "_rels/.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
    "xl/workbook.xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${safeSheet}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
    "xl/_rels/workbook.xml.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`,
    "xl/worksheets/sheet1.xml": makeWorksheet(rows),
  };
  return zip(files);
}

function unzip(buffer) {
  const data = Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer);
  const eocd = data.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));
  if (eocd < 0) throw new Error("Invalid XLSX archive");
  const centralSize = data.readUInt32LE(eocd + 12);
  const centralOffset = data.readUInt32LE(eocd + 16);
  const out = {};
  let p = centralOffset;
  const end = centralOffset + centralSize;
  while (p < end && data.readUInt32LE(p) === 0x02014b50) {
    const method = data.readUInt16LE(p + 10);
    const compressedSize = data.readUInt32LE(p + 20);
    const uncompressedSize = data.readUInt32LE(p + 24);
    const nameLen = data.readUInt16LE(p + 28);
    const extraLen = data.readUInt16LE(p + 30);
    const commentLen = data.readUInt16LE(p + 32);
    const localOffset = data.readUInt32LE(p + 42);
    const name = data.subarray(p + 46, p + 46 + nameLen).toString("utf8");
    const localNameLen = data.readUInt16LE(localOffset + 26);
    const localExtraLen = data.readUInt16LE(localOffset + 28);
    const start = localOffset + 30 + localNameLen + localExtraLen;
    const compressed = data.subarray(start, start + compressedSize);
    let raw;
    if (method === 0) raw = compressed;
    else if (method === 8) raw = zlib.inflateRawSync(compressed);
    else throw new Error(`Unsupported XLSX compression method: ${method}`);
    if (raw.length !== uncompressedSize) throw new Error(`Corrupt XLSX entry: ${name}`);
    out[name] = raw;
    p += 46 + nameLen + extraLen + commentLen;
  }
  return out;
}

function parseWorksheet(xml, sharedStrings = []) {
  const rows = [];
  for (const rowMatch of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)) {
    const cells = [];
    for (const cellMatch of rowMatch[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)) {
      const attrs = cellMatch[1];
      const body = cellMatch[2];
      const ref = attrs.match(/\br="([A-Z]+\d+)"/)?.[1];
      const idx = columnIndex(ref);
      const type = attrs.match(/\bt="([^"]+)"/)?.[1] || "";
      let value = "";
      if (type === "inlineStr") value = xmlUnescape(body.match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1] || "");
      else {
        const raw = xmlUnescape(body.match(/<v>([\s\S]*?)<\/v>/)?.[1] || "");
        if (type === "s") value = sharedStrings[Number(raw)] ?? raw;
        else value = raw;
      }
      cells[idx >= 0 ? idx : cells.length] = value;
    }
    rows.push(cells);
  }
  return rows;
}

function parseSharedStrings(xml) {
  if (!xml) return [];
  return [...xml.matchAll(/<si>([\s\S]*?)<\/si>/g)].map(m =>
    xmlUnescape([...m[1].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map(x => x[1]).join(""))
  );
}

function readWorkbook(buffer) {
  const files = unzip(buffer);
  const sheet = files["xl/worksheets/sheet1.xml"];
  if (!sheet) throw new Error("XLSX workbook does not contain sheet1");
  return parseWorksheet(sheet.toString("utf8"), parseSharedStrings(files["xl/sharedStrings.xml"]?.toString("utf8")));
}

module.exports = { createWorkbook, readWorkbook };
