#!/usr/bin/env node
"use strict";
const fs=require('fs'),path=require('path'),crypto=require('crypto');const {execFileSync}=require('child_process');
const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');const checks=[];const check=(n,p,d)=>checks.push({n,pass:!!p,d});
const routes=read('server/routes/admin/reference.routes.js'),controller=read('server/controllers/admin/reference.controller.js'),store=read('server/store.js'),publicRoutes=read('server/routes/reference.routes.js'),hashes=read('docs/admin-crud/PHASE1-FILE-HASHES.sha256');
for(const m of ['get','post','patch','delete']) check(`variety admin ${m} route`,new RegExp(`router\\.${m}\\(\\s*["']\\/crop-types\\/:cropTypeId\\/varieties`).test(routes),`${m} nested route exists`);
check('admin authentication middleware',/auth\.authenticate/.test(routes),'authentication required');check('admin role middleware',/auth\.authorizeRoles\(["']admin["']\)/.test(routes),'admin role required');
for(const n of ['listCropVarieties','getCropVariety','createCropVariety','updateCropVariety','deleteCropVariety']) check(`controller ${n}`,new RegExp(n).test(controller),`${n} exists`);
for(const n of ['getCropVarietiesAdmin','findCropVariety','createCropVariety','updateCropVariety','deleteCropVariety']) check(`store ${n}`,new RegExp(`async function ${n}`).test(store),`${n} exists`);
check('nested parent context',/WHERE crop_type_id = \$1 AND id = \$2/.test(store),'varieties are parent-scoped');check('parent validation',/Crop type not found/.test(store),'parent existence is validated');check('variety length validation',/Crop variety name must not exceed 255 characters/.test(store),'255-char limit');check('duplicate database protection',/crop_varieties \(crop_type_id, name\)/.test(read('server/migrations/init.sql')),'composite unique constraint preserved');check('parent move blocked',/Changing a variety crop type is not supported/.test(store),'nested parent is immutable');check('public reference unchanged',crypto.createHash('sha256').update(publicRoutes).digest('hex')===(hashes.match(/^([a-f0-9]+)  server\/routes\/reference\.routes\.js$/m)||['',''])[1],'scout reference router unchanged');
for(const f of ['server/store.js','server/controllers/admin/reference.controller.js','server/routes/admin/reference.routes.js','server/crop-variety.store.test.js','server/admin-crop-variety.controller.test.js','scripts/verify-phase4.js']){try{execFileSync(process.execPath,['--check',path.join(root,f)],{stdio:'ignore'});check(`syntax ${f}`,true,'node --check passed')}catch{check(`syntax ${f}`,false,'node --check failed')}}
const failed=checks.filter(x=>!x.pass);console.log('Scout Report — Phase 4 Crop Variety CRUD Verification');console.log('='.repeat(60));for(const c of checks)console.log(`${c.pass?'PASS':'FAIL'}  ${c.n}${c.d?' — '+c.d:''}`);console.log('-'.repeat(60));console.log(`Checks: ${checks.length}\nPassed: ${checks.length-failed.length}\nFailed: ${failed.length}`);if(failed.length)process.exitCode=1;
